### ISSUE TITLE
hmmm.

### ISSUE THREAD

**Issue by gb23** [learn-co-curriculum/js-advanced-scope-closures-readme#12]
Hey flatiron team, this lesson disappointed.  The written portion did a good job explaining concepts (so kudos for that), but the code was sloppy. Errors were probably just copy/pasted from one example to the next. For instance, there's a marketType variable that just randomly and incorrectly appears about halfway through the lesson;  there are constructors that set variables from parameters that aren't even passed in.  It's a mess (unless, of course, you meant for this to be true:
tennisShoe.manufacturePrice;
//=>"tennis shoe"
but I doubt you did.)

Just literally look at the code, try running it in the console and the errors will be pretty clear.  Thank you.

(Sorry for the 'tough love', but if I submitted this, I would hope someone would call me out on it.)

**Comment by laurkim** [comment]
Hey @gb23 thanks for all your input! The ReadMe is being reviewed, including the code.
