### ISSUE TITLE
Image on lab does not represent example being discussed 

### ISSUE THREAD

**Issue by elbincodes** [learn-co-curriculum/js-advanced-scope-closures-readme#13]
Image on lab does not represent example being discussed 

<img width="1146" alt="screen shot 2017-11-02 at 9 47 02 am" src="https://user-images.githubusercontent.com/30355525/32329325-1d63f3ca-bfb3-11e7-90e3-0dcd206a8127.png">

**Comment by laurkim** [comment]
Haha thanks @elbincodes :)
