### ISSUE TITLE
Wrong parameters, and order in example of class

### ISSUE THREAD

**Issue by mxdavis** [learn-co-curriculum/js-advanced-scope-closures-readme#14]
<img width="388" alt="screen shot 2017-11-09 at 4 18 18 pm" src="https://user-images.githubusercontent.com/12608924/32609884-c79a68e0-c569-11e7-9772-0039ae9ea7eb.png">

`  class Item {
    constructor(name, manufacturePrice){
      this.name = name
      this.manufacturePrice = manufacturePrice
    }
    retailPrice(marketMultiplier){
      return marketMultiplier * this.manufacturePrice;
    }
  }
//undefined
let tennisShoe = new Item('tennis shoe', 30)
//undefined
tennisShoe
//Item {name: "tennis shoe", manufacturePrice: 30}`

**Comment by laurkim** [comment]
Fixed, thanks @mxdavis !
