### ISSUE TITLE
Mismatched params & missing this in code snippets 

### ISSUE THREAD

**Issue by LS-C** [learn-co-curriculum/js-advanced-scope-closures-readme#15]
Hi,

First code snippet under Privacy section line 3 should it be name and manufacturePrice as params?
Same snippet line 10, should function is returning with marketMultiplier param and not marketType.  this is missing before manufacturePrice on line 10.  Similar param mismatch and missing this from Privay section to rest of the lab.

**Comment by laurkim** [comment]
FIxed, thanks @LS-C!
