### ISSUE TITLE
Constructor method is missing a second argument in the last two code examples

### ISSUE THREAD

**Issue by kpiipari** [learn-co-curriculum/js-advanced-scope-closures-readme#16]
I think that the constructor method should take in two arguments (manufacturePrice, **name**) 
<img width="708" alt="screen shot 2017-11-15 at 22 15 39" src="https://user-images.githubusercontent.com/2539039/32863202-9b3ba06e-ca52-11e7-8f43-2c807313ae15.png">

<img width="669" alt="screen shot 2017-11-15 at 22 18 53" src="https://user-images.githubusercontent.com/2539039/32863358-1b3c516e-ca53-11e7-87d8-41855a301ebb.png">

**Comment by laurkim** [comment]
Fixed, thanks @kpiipari !
