### ISSUE TITLE
Tests for "createDriver()" not rendering ... browser says "all tests passed"

### ISSUE THREAD

**Issue by dj-sf** [learn-co-curriculum/js-advanced-scope-closures-readme#17]
Example images below.  Not sure if this is affecting other people as well.  I tried shutting down the server and restarting it etc.

![image](https://user-images.githubusercontent.com/30304653/33046773-8826296e-ce20-11e7-8e71-5f2e7ac2249f.png)

![image](https://user-images.githubusercontent.com/30304653/33046816-aca623ca-ce20-11e7-99a6-6a5aa9e4ebb5.png)

**Comment by laurkim** [comment]
Fixed, thanks @jmstrick93
