### ISSUE TITLE
Wrong screenshot of console used

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/js-advanced-scope-closures-readme#19]
![screen shot 2017-12-13 at 11 06 28 pm](https://user-images.githubusercontent.com/28611492/33975089-4f7b0638-e05a-11e7-9242-1a1fc7b60486.png)
This image does not fit the context of the lab. The function names in this image must be from a different lab.

**Comment by laurkim** [comment]
Fixed, thanks @bmcilhenny !
