### ISSUE TITLE
wrong arguments in tennis shoe example

### ISSUE THREAD

**Issue by meebenitez** [learn-co-curriculum/js-advanced-scope-closures-readme#21]
This code does not work as the example shows it.  It's passing the wrong arguments for the constructor:

function createItem(){
  let ItemId = 0
  // return the class
  return class {
    constructor(manufacturePrice){
      this.name = name
      this.manufacturePrice = manufacturePrice
      this.id = ++ItemId;
    }
 
    retailPrice(marketType){
      return marketMultiplier * manufacturePrice;
    }
  }
}
 
const Item = createItem()
// Execute createItem and assign the returned class to equal Item.
// We only need to call createItem() one time in our codebase.
 
let tennisShoe = new Item('tennis shoe', 15)
// {id: 1, name: 'tennis shoe', manufacturePrice: 15}
 
let tshirt = new Item('t shirt', 8)
// {id: 2, name: 't shirt', manufacturePrice: 8}

**Comment by laurkim** [comment]
Fixed, thanks @meebenitez !
