### ISSUE TITLE
Code example uses parameter 'marketType' where it should probably be 'marketMultiplier'

### ISSUE THREAD

**Issue by cnlucke** [learn-co-curriculum/js-advanced-scope-closures-readme#23]
The return function in the example starts out as:

```
  return function(**marketMultiplier**){
    return marketMultiplier * manufacturePrice;
  }

```
Yet, further down the page, the return function suddenly becomes:

```
  return function(**marketType**){
    return marketMultiplier * manufacturePrice;
  }

```
It's not clear why the function parameter of marketMultiplier was renamed to marketType. Yet, the examples behave functionally as though marketType says marketMultiplier instead. For example:

```
function retailPriceMaker(manufacturePrice){
  return function(marketType){
    return marketMultiplier * manufacturePrice;
  }
}
 
const retailPriceForNine = retailPriceMaker(9)
 
const retailPriceForSixteen = retailPriceMaker(16)
 
retailPriceForNine(2)
// 18
 
retailPriceForSixteen(1.5)
// 24

```

When I run that exact code in my console I get "Uncaught ReferenceError: marketMultiplier is not defined".

Thanks!

**Comment by laurkim** [comment]
Fixed, thanks @cnlucke !
