### ISSUE TITLE
Debugger example walks through wrong code snippet

### ISSUE THREAD

**Issue by cnlucke** [learn-co-curriculum/js-advanced-scope-closures-readme#24]
The lesson walks through the code to demonstrate execution scope using the debugger, however, the code used in the debugger image does not match the code used in the rest of the lesson. Shouldn't it be walking through:

```
function retailPriceMaker(manufacturePrice){
  return function(marketMultiplier){
    return marketMultiplier * manufacturePrice;
  }
}
 
const retailPriceForNine = retailPriceMaker(9)
```
rather than the VolumeMaker function?

Thanks!

**Comment by laurkim** [comment]
Fixed, thanks @cnlucke !
