### ISSUE TITLE
typos/grammar

### ISSUE THREAD

**Issue by cs-j** [learn-co-curriculum/js-advanced-scope-closures-readme#27]
For example, above our tennisShoe by 1.5 to accommodate for our New York and LA markets.
=> was multiplied by 1.5

Placing a debugger into our code and running it in our chrome console show us.
=> shows

So just like we can return a function called retailPriceForNine and then see the retailPricereturned with various marketMultipliers passed through, we can construct another function called retailPriceForSixteen for say a different Item.
=> for, say, a different Item. 

But we our attributes can be made truly private when using a closure.
=> But our

**Comment by laurkim** [comment]
Thanks for pointing out all these typos cam. Fixed! @cs-j 👍
