### ISSUE TITLE
Incorrect parameter variable listed in return value

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-advanced-scope-closures-readme#28]
The parameter marketType is used here and there, but seems like it was supposed to be changed to marketMultiplier at some point. Most if not all of the times it is used as an argument name it is being used in reference to the marketMultiplier variable in the body of the function. This is likely a holdover from an edit that was not done properly. marketType is a misnomer and should be fixed.

example: (one of many)
`retailPrice(marketType){`
 `   return marketMultiplier * manufacturePrice`
 ` } `

**Comment by laurkim** [comment]
Thanks for bringing this lab to our attention @LaneMiller ! It is now in the process of being updated thanks to your quick eye! 👍
