### ISSUE TITLE
readMe out of date

### ISSUE THREAD

**Issue by laurkim** [learn-co-curriculum/js-advanced-scope-closures-readme#30]
There are errors in various code blocks that need to be updated because the return value for the code snippets do not match what is given in the readme. One of the screenshots for code was outdated with a function that no longer exists in this lab. There were also some minor typos that I just fixed as I was updating the code snippets.

**Comment by DanielSeehausen** [comment]
thank you @laurkim 

bringing in PRs now and just fixed one myself. guessing its addressed in the PRs :)
