### ISSUE TITLE
broken photo reference

### ISSUE THREAD

**Issue by wley3337** [learn-co-curriculum/js-advanced-scope-closures-readme#33]
retailPriceMaker image doesn't display

just after : 

And if you type the manufacturePrice into the console, you will see that it is not defined in the current global scope. Yet, somehow, when we execute this retailPriceForNine function it knows that the manufacturePrice is 9. It knows this, even though retailPriceForNine points to a function that does not have the variable defined in its execution scope. So how does the function have a value for manufacturePrice? Placing a debugger into our code and running it in our chrome console shows us.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @wley3337.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue.
