### ISSUE TITLE
Typo fix 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-advanced-scope-closures-readme#34]
an item will be 3, and we want to experiment with it's price in different 

So now, by invoking retailPriceMaker we return a function that has it's own unique attribute of a manufacturePrice. And we use 

in both cases -- it's should be its, no apostrophe

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
