### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-advanced-scope-closures-readme#35]
Broken image link:

```retailPriceMaker```

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @AkaKuro4Ever.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
