### ISSUE TITLE
Broken image.

### ISSUE THREAD

**Issue by drkhalid** [learn-co-curriculum/js-advanced-scope-closures-readme#36]
the image inside this subject is broken. its link is not correct. it should be like this in html,
(img alt="retailPriceMaker" src="https://camo.githubusercontent.com/805aeae7f66af215ad31d9858fc2dab6cfb3bfe1/68747470733a2f2f637572726963756c756d2d636f6e74656e742e73332e616d617a6f6e6177732e636f6d2f7765622d646576656c6f706d656e742f6a732f616476616e6365642d73636f70652f636c6f73757265732d726561646d652f6368726f6d652d64656275676765722d636c6f73757265732e706e67").

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @drkhalid.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
