### ISSUE TITLE
This lesson is very poorly written.

### ISSUE THREAD

**Issue by DGMarkel** [learn-co-curriculum/js-advanced-scope-closures-readme#37]
In particular, this paragraph:

So now, by invoking retailPriceMaker we return a function that has it's own unique attribute of a manufacturePrice. And we use this attribute at a later time. So just like we earlier defined a Item class returns objects with a manufacturePrice, here we defined a function that returns functions that has a manufacturePrice. The difference is we avoided a lot of code of declaring a class by just giving this function knowledge of manufacturePrice. So in JavaScript, functions can hold onto state in the same way that objects can. This makes sense, as functions are first class objects.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @DGMarkel.

We have updated this paragraph for clarity and grammar, will be reworking this section of lessons in the near future and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
