### ISSUE TITLE
Proofreading fix

### ISSUE THREAD

**Issue by arianaberger** [learn-co-curriculum/js-advanced-scope-closures-readme#39]
So using closures allows **us** to construct a class that has access to variables that are only available to functions that referenced the variable when the functions were declared.

"us" was missing

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this
issue. 💙
