### ISSUE TITLE
Fix the grammar here

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/js-advanced-scope-closures-readme#42]
For these sentences:
"So here, our returned functions provides some capability that JavaScript objects do not. Encapsulation."

"Provides" should be singular and "encapsulation" should not be a standalone word. Suggested edit:
"So here, our returned functions provide some capability that JavaScript objects do not: encapsulation."

Thank you.

**Comment by drakeltheryuujin** [comment]
We have updated the materials and believe the issue to have been resolved.
